source 'https://rubygems.org'

gem 'rails', '4.2.7.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem "dotenv-rails", require: "dotenv/rails-now"
gem "robinhood-ruby", path: "../.."

group :development, :test do
  gem 'pry'
  gem 'byebug'
end
